name: CI-windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]


    steps:
    - uses: actions/checkout@v3

    - name: Set up Conan
      uses: imesense/gha-setup-conan@v0.1
      with:
        version: '2.12.2'

    - name: Install dependencies
      run: |
       conan profile detect
       conan install . --output-folder=build --build=missing
       
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: |
        cd build
        cmake .. -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake  -DCMAKE_POLICY_DEFAULT_CMP0091=NEW 
        MSBuild.exe your_project_name.sln

    # - name: Run Tests
    #  run: |
    #    ctest --test-dir build
